# Generated by Django 5.2.8 on 2025-12-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancerequest_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('for approval', 'for approval'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='for approval', max_length=20),
        ),
    ]
