# Generated by Django 5.2.8 on 2025-12-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_maintenancerequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('staff', 'Staff')], max_length=20),
        ),
    ]
