# Generated by Django 5.2.8 on 2025-12-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_maintenancerequest_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='section',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='student_id',
        ),
    ]
