# Generated by Django 5.2.8 on 2025-12-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_maintenancerequest_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
