# Generated by Django 5.2.8 on 2025-12-13 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_maintenancerequest_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='requester_name',
            field=models.CharField(blank=True, help_text='Name of the person requesting maintenance', max_length=255, null=True),
        ),
    ]
